services:
  api:
    build: .
    container_name: shop_fastapi
    restart: always
    environment:
      DATABASE_URI: ${DATABASE_URI}
      ORIGINS: ${ORIGINS}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: ${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
    ports:
      - "8000:8000"

networks:
  default:
    ipam:
      config:
        - subnet: 172.30.0.0/16
