services:
  postgres_db:
    image: postgres:17-alpine
    container_name: shop_postgres
    restart: always
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: shop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: .
    container_name: shop_fastapi
    restart: always
    environment:
      DATABASE_URL: "postgresql+asyncpg://local_user:local_password@localhost:5432/shop_db"
      ORIGINS: "http://localhost:3000"
      JWT_SECRET_KEY:  "b9ee58e91fa4808ac30b5dc73318319942d1980a99eb07a167368a1ab455a087"
      JWT_ALGORITHM: "HS256"
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
volumes:
  postgres_data: