"""empty message

Revision ID: 3b6b2c1c1708
Revises: bf844adc160c
Create Date: 2026-07-03 22:06:56.885735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6b2c1c1708'
down_revision = 'bf844adc160c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('image', if_exists=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
