"""add thumbnail to product variant

Revision ID: 7da593b1eb38
Revises: 9e78fb346339
Create Date: 2026-07-21 16:25:27.204539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da593b1eb38'
down_revision = '9e78fb346339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('thumbnail', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'thumbnail')
    # ### end Alembic commands ###
