"""initial

Revision ID: 9e78fb346339
Revises: c90fcc571617
Create Date: 2026-07-21 10:48:24.673967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e78fb346339'
down_revision = 'c90fcc571617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('variant_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_cart_item_slug'), 'cart_items', type_='unique')
    op.create_unique_constraint('uq_cart_item', 'cart_items', ['cart_id', 'variant_id'])
    op.drop_constraint(op.f('cart_items_product_id_fkey'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'product_variants', ['variant_id'], ['id'])
    op.drop_column('cart_items', 'product_id')
    op.drop_column('cart_items', 'slug')
    op.add_column('categories', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.drop_column('categories', 'image')
    op.add_column('order_items', sa.Column('variant_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('order_items_product_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'product_variants', ['variant_id'], ['id'])
    op.drop_column('order_items', 'product_id')
    op.drop_column('order_items', 'slug')
    op.execute("CREATE TYPE user_role_enum AS ENUM ('customer', 'admin')")
    op.execute("""
    ALTER TABLE users
    ALTER COLUMN role TYPE user_role_enum
    USING role::text::user_role_enum
""")
    op.alter_column('users', 'role',
                existing_type=postgresql.ENUM('customer', 'admin', name='role'),
                type_=sa.Enum('customer', 'admin', name='user_role_enum'),
                existing_nullable=False)
    op.execute("DROP TYPE IF EXISTS role")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('customer', 'admin', name='user_role_enum'),
               type_=postgresql.ENUM('customer', 'admin', name='role'),
               existing_nullable=False)
    op.add_column('order_items', sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_product_id_fkey'), 'order_items', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.drop_column('order_items', 'variant_id')
    op.add_column('categories', sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('categories', 'image_url')
    op.add_column('cart_items', sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('cart_items', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('cart_items_product_id_fkey'), 'cart_items', 'products', ['product_id'], ['id'])
    op.drop_constraint('uq_cart_item', 'cart_items', type_='unique')
    op.create_unique_constraint(op.f('uq_cart_item_slug'), 'cart_items', ['cart_id', 'slug'], postgresql_nulls_not_distinct=False)
    op.drop_column('cart_items', 'variant_id')
    # ### end Alembic commands ###
