"""add stripe_payment_id, change values of OrderStatus

Revision ID: ab666f0f5992
Revises: a4b9b2c18802
Create Date: 2026-10-05 17:46:29.158629

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ab666f0f5992"
down_revision = "a4b9b2c18802"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("stripe_payment_intent_id", sa.String(length=256), nullable=True),
    )
    op.create_index(
        op.f("ix_orders_stripe_payment_intent_id"),
        "orders",
        ["stripe_payment_intent_id"],
        unique=True,
    )
    op.execute("DROP TYPE IF EXISTS orderstatus CASCADE")
    op.execute(
        "CREATE TYPE orderstatus AS ENUM ('processing', 'paid', 'canceled', 'created', 'failed')"
    )
    op.add_column(
        "orders",
        sa.Column(
            "status",
            sa.Enum(
                "processing",
                "paid",
                "canceled",
                "created",
                "failed",
                name="orderstatus",
            ),
            nullable=False,
            server_default="processing",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_stripe_payment_intent_id"), table_name="orders")
    op.drop_column("orders", "stripe_payment_intent_id")
    op.drop_column("orders", "status")
    sa.Column(
        "status",
        sa.Enum("pending", "paid", "delivered", name="orderstatus"),
        nullable=False,
    )
    op.execute("DROP TYPE IF EXISTS orderstatus")
    # ### end Alembic commands ###
